name: Go test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v2
      # Goのセットアップ
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
      # Goアプリケーションのビルド
      - name: Build
        run: go build -v ./...
      # テストを実行
      - name: Tests

        run: go test -v ./...